### ISSUE TITLE
Mounting NFS Volume: permission denied

### ISSUE THREAD

**Issue by AJNOURI** [AJNOURI/Docker_Certified_Associate_Certification#10]
Created volume with docker NFS driver
`[ajn@manager1 ~]$ docker volume create --driver local --opt type=nfs --opt o=addr=192.168.0.146,rw --opt device=:/var/nfs/general native-nfs`

Tried to run a container that mount a local directory to NFS volume
`[ajn@manager1 ~]$ docker run --rm -it -v native-nfs:/mnt alpine`

> docker: Error response from daemon: error while mounting volume with options: type='nfs' device=':/nfs' o='addr=192.168.0.146,rw': permission denied.

**Comment by AJNOURI** [comment]
After inspecting **NFS server** configuration:
`ajn@/$ cat /etc/exports`

> /var/nfs/general     *(rw,sync,no_subtree_check)

The shared directory is different from the one used in swarm manager
`device=:/nfs `    and  `/var/nfs/general `

First I had to remove the erroneous volume
`[ajn@manager1 ~]$ docker volume rm native-nfs`

> native-nfs

`[ajn@manager1 ~]$ docker volume ls`

> DRIVER              VOLUME NAME

So set the correct shared directory
`[ajn@manager1 ~]$ docker volume create --driver local --opt type=nfs --opt o=addr=192.168.0.146,rw --opt device=:**/var/nfs/general** native-nfs`

Now everything works fine
docker run --rm -it -v native-nfs:/mnt alpine

**Comment by tekatool** [comment]
I am having a similar issue which I can't seem to resolve.

when I do docker run -v  mynfs-gw:/home/somedir/repo/svr    ...
getting docker: Error response from daemon: error while mounting volume with options: type='nfs' device=':/home/nfs-export-gw' o='addr=10.204.131.34,hard,nolock,rw': permission denied.


Config NFS 4 
on Server sles 12-2: 
 I've exported /etc/exports
 /home/nfs-export-apim   *(rw,no_root_squash,sync,no_subtree_check)
/home/nfs-export-gw     *(rw,no_root_squash,sync,no_subtree_check)


On Client sles12-3: [docker 17.09 ubuntu 16.04] - using a different user [usrA] in docker container with no special drivers

sudo docker volume create --driver local --opt type=nfs --opt o=addr=10.204.131.34,hard,nolock,rw --opt device=:/home/nfs-export-gw mynfs-gw

docker volume inspect
[
    {
        "CreatedAt": "2018-09-12T17:50:14-06:00",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/mynfs-gw/_data",
        "Name": "mynfs-gw",
        "Options": {
            "device": ":/home/nfs-export-gw",
            "o": "addr=10.204.131.34,hard,nolock,rw",
            "type": "nfs"
        },
        "Scope": "local"
    }
]
